language: node_js
node_js:
  - lts/*
before_install:
  - npm install -g vuepress
install:
  - yarn install # npm ci
script:
  - ./
  deploy.sh
notifications:
  email:
    - 2662419405@qq.com
  on_success: change
  on_failure: always